### ISSUE TITLE
Tests for 4.3 not passing in Windows

### ISSUE THREAD

**Issue by janbrohl** [janbrohl/SimpleTAL#1]
```
...................FFFFF...................................................................................................................................................................................................................................................................................F...........................................................F..........EE.E.
======================================================================
ERROR: testExplicitXMLTemplateCache (TestModule44.TemplateCacheTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TALUtilsTests\TemplateCacheTestCases.py", line 209, in testExplicitXMLTemplateCache
    tf = open (name, 'w')
IOError: [Errno 2] No such file or directory: '/tmp/TemplateCacheTestCasesXmlTemplate.xhtml'

======================================================================
ERROR: testHTMLTemplateCache (TestModule44.TemplateCacheTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TALUtilsTests\TemplateCacheTestCases.py", line 86, in testHTMLTemplateCache
    tf = open (name, 'w')
IOError: [Errno 2] No such file or directory: '/tmp/TemplateCacheTestCasesHtmlTemplate.html'

======================================================================
ERROR: testXMLTemplateCache (TestModule44.TemplateCacheTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TALUtilsTests\TemplateCacheTestCases.py", line 155, in testXMLTemplateCache
    tf = open (name, 'w')
IOError: [Errno 2] No such file or directory: '/tmp/TemplateCacheTestCasesXmlTemplate.xml'

======================================================================
FAIL: testMacroTALDefinition (TestModule4.DefineMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 124, in testMacroTALDefinition
    ,"TAL Command on a macro failed.")
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 71, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, pageTemplate))
AssertionError: TAL Command on a macro failed. - 
passed in: <html><p metal:define-macro="one" tal:content="test">Wibble</p></html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<p>testing</p>
<br />
</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<p>testing</p>
<br></br>
</html>

Template: Commands:

[0] (9, u'<html>\n')
[1] (8, ({u'metal:use-macro': u'site/macros/one'}, []))
[2] 14, (site/macros/one{title: SubTemplate from 5 to 8
}, 2)
[3] (10, (u'body', 0))
[4] (9, u'\n')
[5] (8, ({u'metal:fill-slot': u'title'}, []))
[6] (10, (u'h1', 0))
[7] (9, u'Expansion of macro one')
[8] (11, (u'h1', 0, 0))
[9] (9, u'\n')
[10] (11, (u'body', 0, 0))
[11] (9, u'\n<br />\n</html>')

Symbols:
Symbol: 2 points to: 10, which is command: (11, (u'body', 0, 0))
Symbol: 3 points to: 8, which is command: (11, (u'h1', 0, 0))


Macros:


======================================================================
FAIL: testNestedMacroDefinition (TestModule4.DefineMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 109, in testNestedMacroDefinition
    ,"Nested macro with no slots failed.")
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 71, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, pageTemplate))
AssertionError: Nested macro with no slots failed. - 
passed in: <html><div metal:define-macro="two" class="funny"><body metal:define-macro="one">A second macro</body>No slots here</div></html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<body>A second macro</body>
<br />
</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<body>A second macro</body>
<br></br>
</html>

Template: Commands:

[0] (9, u'<html>\n')
[1] (8, ({u'metal:use-macro': u'site/macros/one'}, []))
[2] 14, (site/macros/one{title: SubTemplate from 5 to 8
}, 2)
[3] (10, (u'body', 0))
[4] (9, u'\n')
[5] (8, ({u'metal:fill-slot': u'title'}, []))
[6] (10, (u'h1', 0))
[7] (9, u'Expansion of macro one')
[8] (11, (u'h1', 0, 0))
[9] (9, u'\n')
[10] (11, (u'body', 0, 0))
[11] (9, u'\n<br />\n</html>')

Symbols:
Symbol: 2 points to: 10, which is command: (11, (u'body', 0, 0))
Symbol: 3 points to: 8, which is command: (11, (u'h1', 0, 0))


Macros:


======================================================================
FAIL: testSingleMacroDefinition (TestModule4.DefineMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 89, in testSingleMacroDefinition
    ,"Single macro with no slots failed.")
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 71, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, pageTemplate))
AssertionError: Single macro with no slots failed. - 
passed in: <html><div metal:define-macro="one" class="funny">No slots here</div></html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<div class="funny">No slots here</div>
<br />
</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<div class="funny">No slots here</div>
<br></br>
</html>

Template: Commands:

[0] (9, u'<html>\n')
[1] (8, ({u'metal:use-macro': u'site/macros/one'}, []))
[2] 14, (site/macros/one{title: SubTemplate from 5 to 8
}, 2)
[3] (10, (u'body', 0))
[4] (9, u'\n')
[5] (8, ({u'metal:fill-slot': u'title'}, []))
[6] (10, (u'h1', 0))
[7] (9, u'Expansion of macro one')
[8] (11, (u'h1', 0, 0))
[9] (9, u'\n')
[10] (11, (u'body', 0, 0))
[11] (9, u'\n<br />\n</html>')

Symbols:
Symbol: 2 points to: 10, which is command: (11, (u'body', 0, 0))
Symbol: 3 points to: 8, which is command: (11, (u'h1', 0, 0))


Macros:


======================================================================
FAIL: testSingletonMacros (TestModule4.DefineMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 134, in testSingletonMacros
    ,"Singleton inside slot failed.")
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 71, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, pageTemplate))
AssertionError: Singleton inside slot failed. - 
passed in: <html><p metal:define-macro="one">Wibble<br/></p></html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<p>Wibble<br /></p>
<br />
</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<p>Wibble<br></br></p>
<br></br>
</html>

Template: Commands:

[0] (9, u'<html>\n')
[1] (8, ({u'metal:use-macro': u'site/macros/one'}, []))
[2] 14, (site/macros/one{title: SubTemplate from 5 to 8
}, 2)
[3] (10, (u'body', 0))
[4] (9, u'\n')
[5] (8, ({u'metal:fill-slot': u'title'}, []))
[6] (10, (u'h1', 0))
[7] (9, u'Expansion of macro one')
[8] (11, (u'h1', 0, 0))
[9] (9, u'\n')
[10] (11, (u'body', 0, 0))
[11] (9, u'\n<br />\n</html>')

Symbols:
Symbol: 2 points to: 10, which is command: (11, (u'body', 0, 0))
Symbol: 3 points to: 8, which is command: (11, (u'h1', 0, 0))


Macros:


======================================================================
FAIL: testTwoMacroDefinition (TestModule4.DefineMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 99, in testTwoMacroDefinition
    ,"Two macros with no slots failed.")
  File "tests\METALTests\XMLTests\DefineMacroTests.py", line 71, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, pageTemplate))
AssertionError: Two macros with no slots failed. - 
passed in: <html><body metal:define-macro="two">A second macro</body><div metal:define-macro="one" class="funny">No slots here</div></html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<div class="funny">No slots here</div>
<br />
</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<html>
<div class="funny">No slots here</div>
<br></br>
</html>

Template: Commands:

[0] (9, u'<html>\n')
[1] (8, ({u'metal:use-macro': u'site/macros/one'}, []))
[2] 14, (site/macros/one{title: SubTemplate from 5 to 8
}, 2)
[3] (10, (u'body', 0))
[4] (9, u'\n')
[5] (8, ({u'metal:fill-slot': u'title'}, []))
[6] (10, (u'h1', 0))
[7] (9, u'Expansion of macro one')
[8] (11, (u'h1', 0, 0))
[9] (9, u'\n')
[10] (11, (u'body', 0, 0))
[11] (9, u'\n<br />\n</html>')

Symbols:
Symbol: 2 points to: 10, which is command: (11, (u'body', 0, 0))
Symbol: 3 points to: 8, which is command: (11, (u'h1', 0, 0))


Macros:


======================================================================
FAIL: testNBSPparsing (TestModule36.TALHandlerTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TALTests\XMLTests\TALHandlerTestCases.py", line 226, in testNBSPparsing
    self.failUnless (realResult == expectedResult, "NBSP expansion failed - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (txt, realResult, expectedResult, template))
AssertionError: NBSP expansion failed - 
passed in: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html><p>Test&nbsp;Space</p></html> 
got back <?xml version="1.0"?>
<html><p>TestÂ Space</p></html> 
expected <?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html><p>TestÂ Space</p></html>

Template: Commands:

[0] (9, u'<html><p>Test\xa0Space</p></html>')

Symbols:


Macros:


======================================================================
FAIL: testAmpInTemplate (TestModule41.TALSpecialCharsTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TALTests\XMLTests\TALSpecialCharsTestCases.py", line 77, in testAmpInTemplate
    ,"&amp; in template failed.")
  File "tests\TALTests\XMLTests\TALSpecialCharsTestCases.py", line 57, in _runTest_
    self.failUnless (realResult == result, "%s - \npassed in: %s \ngot back %s \nexpected %s\n\nTemplate: %s" % (errMsg, txt, realResult, result, template))
AssertionError: &amp; in template failed. - 
passed in: <!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html test="&amp;" tal:attributes="test2 string: Boo There ${test}">Hello Bye Bye</html> 
got back <?xml version="1.0" encoding="iso-8859-1"?>
<html test2="Boo There &lt; testing &gt; experimenting &amp; twice as useful" test="&amp;">Hello Bye Bye</html> 
expected <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html test2="Boo There &lt; testing &gt; experimenting &amp; twice as useful" test="&amp;">Hello Bye Bye</html>

Template: Commands:

[0] (8, ({u'test': u'&', u'tal:attributes': u'test2 string: Boo There ${test}'}, [(u'test', u'&')]))
[1] (6, [(u'test2', u'string: Boo There ${test}')])
[2] (10, (u'html', 0))
[3] (9, u'Hello Bye Bye')
[4] (11, (u'html', 0, 0))

Symbols:
Symbol: 2 points to: 4, which is command: (11, (u'html', 0, 0))


Macros:


----------------------------------------------------------------------
Ran 375 tests in 6.361s

FAILED (failures=7, errors=3)
```

**Comment by janbrohl** [comment]
Fixed in 8acb127a2baf2968f40117e96d5568246f40aec0
